# Generated by Erlang.mk. Edit at your own risk!

src/DNS-ASN1.erl:: include/DNS-ASN1.hrl; @touch $@
src/dns.erl:: include/dns.hrl include/dns_records.hrl include/dns_terms.hrl include/dns_tests.hrl include/rebar_version.hrl; @touch $@
src/dns_record.erl:: include/dns.hrl include/dns_records.hrl include/dns_terms.hrl include/rebar_version.hrl; @touch $@
src/dns_record_info.erl:: include/dns_records.hrl include/dns_terms.hrl include/rebar_version.hrl; @touch $@
src/dnssec.erl:: include/DNS-ASN1.hrl include/dns.hrl include/dns_records.hrl include/dns_terms.hrl include/dnssec_tests.hrl include/rebar_version.hrl; @touch $@

COMPILE_FIRST +=
